---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    member_search_pattern: ".*{{ target }}$"

  pre_tasks:

    - name: authenticate to cloud
      os_auth:
        cloud: "{{ os_client_target }}"

  tasks:

    - name: list load-balancer pools
      shell: neutron --os-cloud={{ os_client_target }} lbaas-pool-list -f json
      register: pool_list
      tags: lbaas

    - set_fact:
        pools: "{{ pool_list.stdout|from_json }}"
      tags: lbaas

    - set_fact:
        pool: true
      when: pools|length > 0 and pools|selectattr("name", "match", "load-balancer-pool")|list|length > 0
      tags: lbaas

    - block:

        - name: list pool members
          shell: neutron --os-cloud={{ os_client_target }} lbaas-member-list load-balancer-pool -f json
          register: member_list

        - set_fact:
            members: "{{ member_list.stdout|from_json|selectattr('name', 'match', member_search_pattern)|list }}"

        - name: remove pool members
          shell: neutron --os-cloud={{ os_client_target }} lbaas-member-delete {{ item.name }} load-balancer-pool
          with_items:
            - "{{ members | default([]) }}"
          when: members is defined

        - name: delete pool
          shell: neutron --os-cloud={{ os_client_target }} lbaas-pool-delete load-balancer-pool

      when: pool is defined
      tags: lbaas

    - name: list load balancer listeners
      shell: neutron --os-cloud={{ os_client_target }} lbaas-listener-list -f json
      register: listener_instances
      tags: lbaas

    - set_fact:
        listener_instance: "{{ listener_instances.stdout|from_json|selectattr('name', 'match', 'load-balancer-listener')|list }}"
      when: listener_instances.stdout|from_json|length > 0
      tags: lbaas

    - name: delete load balancer listener
      shell: neutron --os-cloud={{ os_client_target }} lbaas-listener-delete load-balancer-listener
      when: listener_instance is defined
      tags: lbaas

    - name: list load balancer
      shell: neutron --os-cloud={{ os_client_target }} lbaas-loadbalancer-list -f json
      register: lbaas_instances
      tags: lbaas

    - set_fact:
        lbaas_instance: "{{ lbaas_instances.stdout|from_json|selectattr('name', 'match', 'load-balancer')|list }}"
      when: lbaas_instances.stdout|from_json|length > 0
      tags: lbaas

    - name: get load balancer facts
      shell: neutron --os-cloud={{ os_client_target }} lbaas-loadbalancer-show load-balancer -f json
      register: load_balancer_facts
      when: lbaas_instance is defined

    - set_fact:
        lbaas_instance_detail: "{{ load_balancer_facts.stdout|from_json }}"
      when: lbaas_instance is defined

    - name: check for floating ip associated to load balancer
      shell: neutron --os-cloud={{ os_client_target }} floatingip-list -f json
      register: floatingip_list
      when: lbaas_instance is defined

    - set_fact:
        floatingips: "{{ floatingip_list.stdout|from_json }}"
      when: lbaas_instance is defined

    - set_fact:
        floatingip: "{{ floatingips|selectattr('port_id', 'match', lbaas_instance_detail.vip_port_id)|first }}"
      when: lbaas_instance is defined and floatingips|length > 0 and floatingips|selectattr('port_id', 'match', lbaas_instance_detail.vip_port_id)|list|length > 0

    - name: delete load balancer
      shell: neutron --os-cloud={{ os_client_target }} lbaas-loadbalancer-delete load-balancer
      when: lbaas_instance is defined
      tags: lbaas

    - name: disassociate floating ip from load balancer
      shell: neutron --os-cloud={{ os_client_target }} floatingip-delete {{ floatingip.id }}
      register: floatingip_association
      when: floatingip is defined

    - name: delete servers
      os_server:
        name: "{{ item }}-{{ target }}"
        delete_fip: yes
        state: absent
        cloud: "{{ os_client_target }}"
      with_items:
        - railsapp-1
        - railsapp-2
        - postgresql
      tags: servers

    - name: delete router
      os_router:
        name: router
        state: absent
        cloud: "{{ os_client_target }}"
      tags: network

    - name: delete networks
      os_network:
        name: "{{ item }}"
        state: absent
        cloud: "{{ os_client_target }}"
      with_items:
        - database
        - web
      tags: network
...
