---

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
     - group_vars/all.yml

  pre_tasks:

    - include_vars:
        file: openstack/keystonerc_production.yaml
      when: target == 'production'

    - include_vars:
        file: openstack/keystonerc_staging.yaml
      when: target == 'staging'

    - name: authenticate to cloud
      os_auth:
      environment: "{{ openstack_environment }}"

  tasks:

  - name: create networks
    os_network:
      name: "{{ item }}"
      state: present
    environment: "{{ openstack_environment }}"
    with_items:
      - database
      - web

  - name: create subnets
    os_subnet:
      name: "{{ item.subnet }}"
      network_name: "{{ item.network }}"
      dns_nameservers: "{{ item.dns }}"
      cidr: "{{ item.cidr }}"
      state: present
    environment: "{{ openstack_environment }}"
    with_items:
      - { network: database, subnet: database-subnet, cidr: 172.16.0.0/16, dns: 192.168.26.1 }
      - { network: web, subnet: web-subnet, cidr: 172.17.0.0/16, dns: 192.168.26.1 }

  - name: create router
    os_router:
      name: router
      network: "{{ uplink_name }}"
      interfaces:
        - database-subnet
        - web-subnet
      state: present
    environment: "{{ openstack_environment }}"


...
