---

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
     - group_vars/all.yml

  tasks:

  - include_vars:
      file: openstack/keystonerc_production
    when: target == 'production'

  - include_vars:
      file: openstack/keystonerc_staging
    when: target == 'staging'

  - debug:

  - name: authenticate to cloud
    os_auth:

  environment: "{{ openstack_environment }}"


...
