---

- hosts: web-servers
  serial: 1

  pre_tasks:

    - include: remove_lb_pool_member.yml member={{ openstack.name }}
      delegate_to: localhost

    - name: wait for application endpoint to be drained
      wait_for: host={{ openstack.accessIPv4 }} port=3000 state=drained timeout=60
      delegate_to: localhost

  roles:
    - rails
    - { role: rails-app, postgres: "{{ hostvars[groups['database-server'][0]]['postgres'] }}" }

  post_tasks:

    - name: wait for application endpoint to come up
      wait_for: host={{ openstack.accessIPv4 }} port=3000 state=started timeout=60
      delegate_to: localhost

    - include: add_lb_pool_member.yml member={{ openstack.name }}
      delegate_to: localhost

    - name: pause for demo purposes
      pause:
        seconds: 60

...
