---

- include: provision.yml
  tags: provisioning

- hosts: database-server
  roles:
    - postgres
    - rails-db

- hosts: web-servers
  roles:
    - rails
    - { role: rails-app, postgres: "{{ hostvars[groups['database-server'][0]]['postgres'] }}" }

  tasks:

    - name: wait for application endpoint to come up
      wait_for: host={{ floatingip.floating_ip_address }} port=3000 state=started timeout=10
      delegate_to: localhost

...
