---

- name: create database user {{ postgres.user }}
  shell: psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ postgres.user }}'" | grep -q 1 || createuser {{ postgres.user }}
  become: yes
  become_user: postgres

- name: create database {{ postgres.database }}
  shell: psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{ postgres.database }}'" | grep -q 1 || createdb --owner={{ postgres.user }} {{ postgres.database }}
  become: yes
  become_user: postgres

- name: set database user {{ postgres.user }} password
  shell: psql postgres -tAc "ALTER USER rails with encrypted password '{{ postgres.password }}'"
  become: yes
  become_user: postgres

- name: set database user {{ postgres.user }} permissions
  shell: psql postgres -tAc "GRANT ALL PRIVILEGES ON DATABASE {{ postgres.database }} to {{ postgres.user }}"
  become: yes
  become_user: postgres

...
