---

- name: create database user rails
  shell: psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='rails'" | grep -q 1 || createuser rails
  become: yes
  become_user: postgres

- name: create database rails
  shell: psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname='rails'" | grep -q 1 || createdb --owner=rails rails
  become: yes
  become_user: postgres

- name: set database user rails password
  shell: psql postgres -tAc "ALTER USER rails with encrypted password 'rails'"
  become: yes
  become_user: postgres

- name: set database user rails permissions
  shell: psql postgres -tAc "GRANT ALL PRIVILEGES ON DATABASE rails to rails"
  become: yes
  become_user: postgres

...
